services:
  - type: web
    name: math-chatbot
    env: node
    plan: starter # Plan con más recursos
    buildCommand: npm install --production --legacy-peer-deps
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        value: un_secreto_temporal_muy_largo_y_seguro_para_pruebas
      - key: OPENAI_API_KEY
        value: sk-dummy-key-for-build-only
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=450

